[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = ["cryptography>1.0.0", "pydantic>=2.4.2", "pydantic-settings>=2.0.3", "python-dotenv>=1.0.0",]